# https://gohugo.io/getting-started/configuration/#toml-configuration

# ##################################################
# Hugo-defined variables
baseURL       = "http://localhost:1313/"
title         = "Rolando"
theme         = "hugo-theme-w3css-basic"
languageCode  = "en-us"
#languageCode  = "de-ch"

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"

#disableFastRender=true

# Enable Emoji emoticons support for page content; see emoji-cheat-sheet.com
enableEmoji   = true

# the length of text to show in a .Summary
summaryLength = 70

# Pagination (3,6,9,12, ...)
paginate =  6

# # Enable comments by entering your Disqus shortname
# disqusShortname = "it-gro-github-io-hugo-theme-w3css-basic-github-io"

# https://gohugo.io/content-management/syntax-highlighting/
pygmentsUseClassic            = false
pygmentsCodeFences            = true
pygmentsCodeFencesGuessSyntax = true
pygmentsUseClasses            = true
# => static/css/syntax/syntax/syntax.*.css
# copy one of them to
# static/css/syntax/syntax.css
# alternative (if shortcodes/csc*.html are not used):
# set pygmentsUseClassic to false on choose one of the following:
#pygmentsStyle = "abap"
#pygmentsStyle = "algol"
#pygmentsStyle = "algol_nu"
#pygmentsStyle = "api"
#pygmentsStyle = "arduino"
#pygmentsStyle = "autumn"
#pygmentsStyle = "borland"
#pygmentsStyle = "bw"
#pygmentsStyle = "colorful"
#pygmentsStyle = "default"
#pygmentsStyle = "dracula"
#pygmentsStyle = "emacs"
#pygmentsStyle = "friendly"
#pygmentsStyle = "fruity"
#pygmentsStyle = "github"
#pygmentsStyle = "igor"
#pygmentsStyle = "lovelace"
#pygmentsStyle = "manni"
#pygmentsStyle = "monokai"
#pygmentsStyle = "monokailight"
#pygmentsStyle = "murphy"
#pygmentsStyle = "native"
#pygmentsStyle = "paraiso-dark"
#pygmentsStyle = "paraiso-light"
#pygmentsStyle = "pastie"
#pygmentsStyle = "perldoc"
#pygmentsStyle = "pygments"
#pygmentsStyle = "rainbow_dash"
#pygmentsStyle = "rrt"
#pygmentsStyle = "solarized-dark256"
#pygmentsStyle = "solarized-dark"
#pygmentsStyle = "solarized-light"
#pygmentsStyle = "swapoff"
#pygmentsStyle = "tango"
#pygmentsStyle = "trac"
#pygmentsStyle = "vim"
#pygmentsStyle = "vs"
#pygmentsStyle = "xcode"

# Enable Google Analytics by entering your tracking code
#googleAnalytics = "UA-113314068-2"


# RSS Feed
# Do not build RSS files
disableRSS = false
# maximum number of items in the RSS feed
rssLimit   = 10

[outputs]
home = [ "HTML", "RSS" ]
section = [ "HTML", "RSS"]

[imaging]
# https://gohugo.io/content-management/image-processing/
# Default resample filter used for resizing. Default is Box,
# a simple and fast averaging filter appropriate for downscaling.
# See https://github.com/disintegration/imaging
resampleFilter = "box"

# Defatult JPEG quality setting. Default is 75.
quality = 75

# Anchor used when cropping pictures.
# Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
# Smart Cropping is content aware and tries to find the best crop for each image.
# Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
anchor = "smart"


# ##################################################
# Theme-defined configuration

# ##################################################
# hugo sections

# [taxonomies]
#   tag      = "tags"
#   category = "categories"

# [Permalinks]
#   blog = "/blog/:year/:month/:day/:filename/"
#   # blog = "/blog/:year/:month/:title/"

# [params.marquee]
#   # enable or disable marquee on frontpage
#   enable      = false

[params.jumbotrons]
  # used in layouts/partials/front.jumbotrons.carousel.html
  # enable or disable jumbotrons on frontpage
  # see some examples in 'exampleSite/data/jumbotron'
  enable   = true

[params.photocards]
  # used in layouts/partials/front.photocards.html
  # enable or disable photocards on frontpage
  # see some examples in 'exampleSite/data/photocards'
  enable        = true
  animate       = false
  resImgCmd     = "Resize"
  resImgCmdOpt  = "300x"

[params.features]
  # used in layouts/partials/front.features.html
  # enable or disable features on frontpage
  # see some examples in 'exampleSite/data/features'
  enable   = true
  animate  = false

[params.testimonials]
  # used in layouts/partials/front.testimonials.carousel.html
  # enable or disable testimonials on frontpage
  # see some examples in 'exampleSite/data/testimonials'
  enable   = true
  title    = "Testimonials"
  subtitle = '''
Consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut
labore et dolore magna aliquyam erat, sed diam voluptua. 
             '''

[params.seeMore]
  # used in layouts/partials/front.see_more.html
  # enable or disable see_more on frontpage
  enable    = true
  icon      = "far fa-file-code"
  title     = "Do You want to see More?"
  linkUrl   = "/pages"
  linkText  = "consectetuer adipiscing"
  subtitle  = '''
Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper
suscipit lobortis nisl ut aliquip ex ea commodo consequat.
              '''


# ##################################################
# Main menu
[menu]

[[menu.main]]
  weight = 1
  name   = "Home"
  url    = "/index.html"
  pre    = "fas fa-home"

[[menu.main]]
  weight = 2
  name   = "Contact"
  url    = "/contact"
  pre    = "far fa-address-card"

[[menu.main]]
  weight = 3
  name   = "FAQ"
  url    = "/faq"
  pre    = "far fa-question-circle"
